name: Increment version of updated scrapers

on:
  push:
    branches: [ leia ]
    paths:
      - '**metadata.album.universal**resource.language.**strings.po'
      - '**metadata.artists.universal**resource.language.**strings.po'
      - '**metadata.universal**resource.language.**strings.po'

jobs:
  default:
    if: github.repository == 'xbmc/repo-scrapers'
    runs-on: ubuntu-latest
    name: Increment version of updated scrapers

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.event.repository.name }}

      - name: Checkout Scripts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: xbmc/weblate-supplementary-scripts
          path: scripts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.4

      - name: Increment version of updated scrapers
        run: |
          python3 ../scripts/repo-resources/increment_version.py $HOME/files.json -bv -c
        working-directory: ${{ github.event.repository.name }}

      - name: Create PR for incremented versions
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Scraper add-on versions incremented
          title: Scraper add-on versions incremented
          body: Scraper add-on versions incrementing triggered by ${{ github.sha }}
          branch: inc-ver
          delete-branch: true
          path: ./${{ github.event.repository.name }}
          reviewers: gade01